"""added summary to book model and seed

Revision ID: 01c4c5ed4766
Revises: de45285fa6a8
Create Date: 2025-01-20 23:23:59.869198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c4c5ed4766'
down_revision = 'de45285fa6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_books_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_borrowings_patron_id'), ['patron_id'], unique=False)

    with op.batch_alter_table('patrons', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrons', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_borrowings_patron_id'))
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_author_id'))
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
